import { Position } from "../types/game";

export const PLAYER_ONE_PATH: Position[] = [
	{ x: 39, y: 39, direction: "left", action: ["START"] },
	{ x: 33, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 27, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 21, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 15, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 39, direction: "up", action: ["CHANCE"] },
	{ x: 9, y: 33, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 27, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 21, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 15, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 9, direction: "right", action: ["JAIL"] },
	{ x: 15, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 21, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 27, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 33, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 9, direction: "down", action: ["CHANCE"] },
	{ x: 39, y: 15, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 21, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 27, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 33, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
];

export const PLAYER_TWO_PATH: Position[] = [
	{ x: 39, y: 40, direction: "left", action: ["START"] },
	{ x: 33, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 27, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 21, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 15, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 40, direction: "up", action: ["CHANCE"] },
	{ x: 9, y: 34, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 28, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 22, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 16, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 9, y: 10, direction: "right", action: ["JAIL"] },
	{ x: 15, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 21, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 27, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 33, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 10, direction: "down", action: ["CHANCE"] },
	{ x: 39, y: 16, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 22, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 28, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 39, y: 34, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
];

export const PLAYER_THREE_PATH: Position[] = [
	{ x: 40, y: 39, direction: "left", action: ["START"] },
	{ x: 34, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 28, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 22, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 16, y: 39, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 39, direction: "up", action: ["CHANCE"] },
	{ x: 10, y: 33, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 27, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 21, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 15, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 9, direction: "right", action: ["JAIL"] },
	{ x: 16, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 22, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 28, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 34, y: 9, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 9, direction: "down", action: ["CHANCE"] },
	{ x: 40, y: 15, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 21, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 27, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 33, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
];

export const PLAYER_FOUR_PATH: Position[] = [
	{ x: 40, y: 40, direction: "left", action: ["START"] },
	{ x: 34, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 28, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 22, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 16, y: 40, direction: "left", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 40, direction: "up", action: ["CHANCE"] },
	{ x: 10, y: 34, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 28, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 22, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 16, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 10, direction: "up", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 10, y: 10, direction: "right", action: ["JAIL"] },
	{ x: 16, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 22, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 28, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 34, y: 10, direction: "right", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 10, direction: "down", action: ["CHANCE"] },
	{ x: 40, y: 16, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 22, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 28, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 34, direction: "down", action: ["BUY", "UPGRADE", "PAY_RENT"] },
	{ x: 40, y: 40, direction: "left", action: ["CHANCE"] },
];
